db-host: localhost
db-port: 33066

mybatis:
  codegen:
    enabled: true
    parent_pck: fit.wenchao.autobackup
    author: wc
    db_url: jdbc:mysql://${db-host}:${db-port}/auto-backup?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    db_username: root
    db_password: wc123456
    controller_on: false
server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://${db-host}:${db-port}/auto-backup?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: wc123456